
version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql-servicosdb
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: servicosdb
    ports:
      - "3306:3306"
    networks:
      - mynet
  redis:
    image: redis
    container_name: redis-servicosdb
    ports:
      - "6379:6379"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge